### PR TITLE
typo in username

### PR DESCRIPTION
**Pull request by zhovner**

### CODE REVIEW

**Comment by iceman1001** [comment]
Thanks!

**Comment by zhovner** [comment]
It still ask for username I don't know why.

```
$ brew  install --debug --HEAD proxmark3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/science).
==> Updated Formulae
elasticsearch     gofabric8         grafana           kibana            logstash          mktorrent         notmuch           rancid            ruby-build        stoken            udunits

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/iceman1001/homebrew-proxmark3/proxmark3.rb
==> Installing proxmark3 from iceman1001/proxmark3
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/p7zip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb-compat.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/iceman1001/homebrew-tap/arm-none-eabi-gcc.rb
==> Tapping iceman1001/tap
Cloning into '/usr/local/Homebrew/Library/Taps/iceman1001/homebrew-tap'...
Username for 'https://github.com': 
```

**Comment by iceman1001** [comment]
Looks like the cloning wants to have your login to download? 
This file is basically the same as Chrisfu.

**Comment by zhovner** [comment]
They do simple `git clone URL`. This step shouldn't ask for username.

**Comment by iceman1001** [comment]
very strange,  and it should download the .tar file also instead of clone

**Pull request merged**
